const app=document.getElementById('app');
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const img=(src,alt='')=>`<img src="${esc(src)}" alt="${esc(alt)}" loading="lazy">`;
const icon=(name='')=>`<span class="icon" aria-hidden="true">${name}</span>`;
const colorClass=c=>['red','green','yellow','blue','purple','dark'].includes(c)?c:'red';

function applyTheme(){if(localStorage.getItem('jlm-theme')==='dark')document.documentElement.classList.add('dark')}
function toggleTheme(){document.documentElement.classList.toggle('dark');localStorage.setItem('jlm-theme',document.documentElement.classList.contains('dark')?'dark':'light');updateThemeButton()}
function updateThemeButton(){document.querySelectorAll('.theme-toggle').forEach(b=>{const dark=document.documentElement.classList.contains('dark');b.textContent=dark?'☼':'◐';b.title=dark?'Mode clair':'Mode sombre';b.setAttribute('aria-label',b.title)})}
function toggleMenu(){document.getElementById('mainNav')?.classList.toggle('open')}
applyTheme();

function header(){return `<header class="site-header"><div class="container header-inner"><a class="brand" href="index.html"><img src="assets/logo-jlm.svg" alt="JLM ENSA Khouribga"><span><b>JLM ENSA Khouribga</b><small>${esc(CLUB.tagline)}</small></span></a><div class="ensa-mark"><img src="assets/logo-ensa-real.png" alt="ENSA Khouribga"></div><nav id="mainNav" class="main-nav"><a href="index.html">Accueil</a><a href="a-propos.html">À propos</a><a href="projets.html">Projets</a><a href="actions.html">Actions</a><a href="bureau.html">Bureau</a><a href="galerie.html">Galerie</a></nav><div class="header-actions"><button class="icon-btn theme-toggle" onclick="toggleTheme()"></button><button class="icon-btn menu-toggle" onclick="toggleMenu()" aria-label="Menu">☰</button></div></div></header>`}
function footer(){return `<footer><div class="container footer-top"><div class="footer-brand"><img src="assets/logo-jlm.svg" alt="JLM"><div><b>${esc(CLUB.name)}</b><small>${esc(CLUB.slogan)}</small></div></div><div class="socials"><a href="${esc(CLUB.social.instagram)}">IG</a><a href="${esc(CLUB.social.tiktok)}">TT</a><a href="${esc(CLUB.social.linkedin)}">in</a><a href="${esc(CLUB.social.facebook)}">f</a><a href="${esc(CLUB.social.youtube)}">▶</a></div></div><div class="container footer-bottom"><span>© ${new Date().getFullYear()} ${esc(CLUB.name)}</span><span>Étudiants · Innovation · Impact</span></div></footer>`}
function layout(content){app.innerHTML=header()+`<main>${content}</main>`+footer();updateThemeButton()}
document.addEventListener('click',e=>{if(e.target.closest('.main-nav a'))document.getElementById('mainNav')?.classList.remove('open')});

function heading(title,accent=''){return `<div class="section-heading"><div><span class="kicker">JLM ENSA KHOURIBGA</span><h2>${esc(title)} ${accent?`<em>${esc(accent)}</em>`:''}</h2></div><i></i></div>`}
function hero(title,accent,text,buttons=[],image='assets/hero-campus.svg',compact=false){return `<section class="hero ${compact?'compact':''}" style="--hero:url('${image}')"><div class="hero-shade"></div><div class="container hero-content"><span class="eyebrow">JLM ENSA KHOURIBGA <b></b></span><h1>${esc(title)} <strong>${esc(accent)}</strong></h1><p>${esc(text)}</p>${buttons.length?`<div class="hero-actions">${buttons.map((b,i)=>`<a class="btn ${i?'ghost':''}" href="${esc(b.href)}">${esc(b.label)} <span>→</span></a>`).join('')}</div>`:''}</div></section>`}
function cta(label,href){return `<section class="container cta"><div><span>JLM ENSA KHOURIBGA</span><h2>${esc(label)}</h2><p>Des idées d’aujourd’hui pour un Maroc meilleur demain.</p></div><a class="btn" href="${href}">Découvrir <span>→</span></a></section>`}
function card(item,kind){return `<a class="card" href="${kind==='project'?'projet':'action'}.html?id=${encodeURIComponent(item.id)}"><div class="card-media">${img(item.image,item.title)}<span class="pill ${colorClass(item.color)}">${esc(item.category)}</span></div><div class="card-body"><small>${esc(item.year||'JLM')}</small><h3>${esc(item.title)}</h3><p>${esc(item.short)}</p><b>Découvrir <span>→</span></b></div></a>`}
function filters(id){return `<div class="filters" id="${id}"><button class="active" data-filter="all">Tous</button>${THEMES.map(t=>`<button data-filter="${t.id}">${esc(t.title)}</button>`).join('')}</div>`}
function bindFilters(id){const box=document.getElementById(id);if(!box)return;box.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;box.querySelectorAll('button').forEach(x=>x.classList.remove('active'));b.classList.add('active');const f=b.dataset.filter;document.querySelectorAll('.filter-item').forEach(x=>x.hidden=f!=='all'&&x.dataset.category!==f)})}

function home(){const slides=[['assets/photos/hero/ensa-students-jlm.png','Notre innovation','bâtit la nation','Découvrez les projets, les actions et les étudiants qui font vivre le JLM ENSA Khouribga.'],['assets/photos/hero/ensa-campus.png','JLM ENSA Khouribga','étudiants · impact','Des idées d’aujourd’hui pour un Maroc meilleur demain.']];layout(`<section class="hero home" id="slider">${slides.map((s,i)=>`<div class="slide ${i?'':'active'}" style="--hero:url('${s[0]}')"></div>`).join('')}<div class="hero-shade"></div><div class="container hero-content"><span class="eyebrow">JLM ENSA KHOURIBGA <b></b></span><h1 id="slideTitle">${slides[0][1]} <strong>${slides[0][2]}</strong></h1><p id="slideText">${slides[0][3]}</p><div class="hero-actions"><a class="btn" href="a-propos.html">Découvrir le club <span>→</span></a><a class="btn ghost" href="projets.html">Voir les projets <span>→</span></a></div></div><div class="dots">${slides.map((_,i)=>`<button class="${i?'':'active'}" data-i="${i}"></button>`).join('')}</div></section>
<section class="container section">${heading('Nos','piliers')}<div class="grid four">${CLUB.pillars.map(x=>`<article class="mini-card"><div class="round ${colorClass(x.color)}">${img(x.icon,x.title)}</div><h3>${esc(x.title)}</h3><p>${esc(x.text)}</p></article>`).join('')}</div></section>
<section class="section alt"><div class="container">${heading('Nos','thématiques')}<p class="intro">Six domaines principaux. Les bootcamps, workshops, challenges et événements sont des formats d’activités.</p><div class="grid three">${THEMES.map(t=>`<article class="theme"><div class="theme-icon">${img(t.icon,t.title)}</div><div><h3>${esc(t.title)}</h3><p>${esc(t.description)}</p></div></article>`).join('')}</div></div></section>
<section class="container section">${heading('Formats','d’activités')}<div class="grid four">${ACTIVITY_FORMATS.map(x=>`<article class="format"><div>${img(x.image,x.title)}</div><h3>${esc(x.title)}</h3><p>${esc(x.text)}</p></article>`).join('')}</div></section>
<section class="container section">${heading('Projets','à la une')}<div class="grid three">${PROJECTS.slice(0,3).map(x=>card(x,'project')).join('')}</div><div class="section-link"><a href="projets.html">Voir tous les projets →</a></div></section>
<section class="container section">${heading('Actions','du club')}<div class="grid four">${ACTIONS.map(x=>card(x,'action')).join('')}</div></section>
<section class="container section">${heading('Notre impact','en chiffres')}<div class="stats">${CLUB.stats.map(x=>`<div><b>${esc(x.value)}</b><span>${esc(x.label)}</span></div>`).join('')}</div></section>${cta('Découvrir tous les projets','projets.html')}`);initSlider(slides)}
function initSlider(slides){const root=document.getElementById('slider');if(!root)return;let i=0;const go=n=>{i=(n+slides.length)%slides.length;root.querySelectorAll('.slide').forEach((x,j)=>x.classList.toggle('active',j===i));root.querySelectorAll('.dots button').forEach((x,j)=>x.classList.toggle('active',j===i));document.getElementById('slideTitle').innerHTML=`${esc(slides[i][1])} <strong>${esc(slides[i][2])}</strong>`;document.getElementById('slideText').textContent=slides[i][3]};root.querySelectorAll('.dots button').forEach(b=>b.onclick=()=>go(+b.dataset.i));setInterval(()=>go(i+1),3000)}
function about(){layout(`${hero('À propos','du club','Des étudiants engagés pour un Maroc meilleur demain.',[{label:'Découvrir nos projets',href:'projets.html'}],'assets/photos/hero/ensa-campus.png')}
<section class="container section"><div class="grid two"><article class="info"><div class="round red">◎</div><div><h2>Notre mission</h2><p>${esc(CLUB.mission)}</p></div></article><article class="info"><div class="round green">◉</div><div><h2>Notre vision</h2><p>${esc(CLUB.vision)}</p></div></article></div></section>
<section class="container section">${heading('Notre','histoire')}<article class="prose"><p>${esc(CLUB.history)}</p><p>Cette plateforme rassemble les projets, actions, thématiques et moments forts du club afin de présenter son activité de manière claire et accessible.</p></article></section>
<section class="container section">${heading('Nos','valeurs')}<div class="grid four">${CLUB.values.map(v=>`<article class="mini-card"><div class="round ${colorClass(v.color)}">${img(v.icon,v.title)}</div><h3>${esc(v.title)}</h3><p>${esc(v.text)}</p></article>`).join('')}</div></section>${cta('Explorer les projets et actions','projets.html')}`)}
function listing(kind){const isP=kind==='project',items=isP?PROJECTS:ACTIONS;layout(`${hero(isP?'Nos':'Nos',isP?'projets':'actions',isP?'Des idées concrètes pour un Maroc meilleur demain.':'Des initiatives concrètes sur le terrain.',[{label:isP?'Explorer les projets':'Explorer les actions',href:'#liste'}],'assets/photos/hero/ensa-campus.png',true)}<section class="container section" id="liste">${filters(isP?'projectFilters':'actionFilters')}<div class="grid two cards-grid">${items.map(x=>`<div class="filter-item" data-category="${x.categoryKey}">${card(x,isP?'project':'action')}</div>`).join('')}</div></section>${cta(isP?'Découvrir les actions':'Découvrir les projets',isP?'actions.html':'projets.html')}`);bindFilters(isP?'projectFilters':'actionFilters')}
function team(){layout(`${hero('Le','bureau','Une équipe étudiante engagée pour transformer les idées en actions.',[{label:'Voir la galerie',href:'galerie.html'}],'assets/photos/hero/ensa-students-jlm.png',true)}<section class="container section"><article class="leader"><div>${img(TEAM[0].image,TEAM[0].name)}</div><div><span class="pill red">Présidence</span><h1>${esc(TEAM[0].name)}</h1><h3>${esc(TEAM[0].role)}</h3><p>“Transformer les idées en impact.”</p></div></article></section><section class="container section">${heading('Membres du','bureau')}<div class="grid three">${TEAM.slice(1).map(m=>`<article class="person">${img(m.image,m.name)}<div><span class="round ${colorClass(m.color)}">•</span><h3>${esc(m.name)}</h3><b>${esc(m.role)}</b><small>${esc(m.field)}</small></div></article>`).join('')}</div></section>${cta('Découvrir la vie du club','galerie.html')}`)}
function gallery(){layout(`${hero('Album','photos','Revivez nos moments forts à travers les projets, actions, formations et événements.',[{label:'Explorer',href:'#gallery'}],'assets/photos/hero/ensa-students-jlm.png',true)}<section class="container section" id="gallery">${heading('Galerie','du club')}<div class="filters" id="galleryFilters"><button class="active" data-filter="all">Tous</button>${GALLERY_REAL.map(x=>`<button data-filter="${x.category}">${esc(x.title)}</button>`).join('')}</div><div class="gallery">${GALLERY_REAL.map(x=>`<article class="gallery-item filter-item" data-category="${x.category}">${img(x.image,x.title)}<div><b>${esc(x.title)}</b><span>Voir le moment</span></div></article>`).join('')}</div></section>${cta('Retour à l’accueil','index.html')}`);bindFilters('galleryFilters')}
function detail(item,kind){const isP=kind==='project',back=isP?'projets.html':'actions.html';if(!item){layout(`<section class="container section empty"><h1>${isP?'Projet':'Action'} introuvable</h1><p>L’identifiant demandé ne correspond à aucun contenu.</p><a class="btn" href="${back}">Retour</a></section>`);return}layout(`<section class="container section"><a class="back" href="${back}">← Retour</a><div class="detail-head"><div>${img(item.image,item.title)}</div><article><span class="pill ${colorClass(item.color)}">${esc(item.category)}</span><small>${esc(item.year||'')}</small><h1>${esc(item.title)}</h1><p>${esc(item.short)}</p></article></div><div class="detail-body"><article>${heading('À','propos')}<p>${esc(item.description)}</p>${heading('Objectifs','')}<ul>${item.objectives.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>${heading('Résultats','')}<div class="result-grid">${item.results.map((x,i)=>`<div><b>0${i+1}</b><span>${esc(x)}</span></div>`).join('')}</div>${heading('Équipe','')}<p>${esc(item.team||'Équipe du JLM ENSA Khouribga')}</p></article><aside><span>JLM ENSA KHOURIBGA</span><h3>${isP?'Projet':'Action'}</h3><p>${esc(item.status||'')}</p><a class="btn ghost darkbtn" href="${back}">Retour</a></aside></div></section>${cta('Découvrir la galerie','galerie.html')}`)}
function qr(){layout(`<section class="container section qr"><div>${heading('QR code','du club')}<h1>Scannez pour découvrir le JLM</h1><p>Le QR code pointe automatiquement vers la page d’accueil publiée.</p><code id="qrUrl"></code><button class="btn" onclick="window.print()">Imprimer</button></div><div id="qrcode" class="qrbox">Chargement…</div></section>`);const u=new URL('index.html',location.href);document.getElementById('qrUrl').textContent=u.href;const s=document.createElement('script');s.src='https://cdnjs.cloudflare.com/ajax/libs/qrcodejs/1.0.0/qrcode.min.js';s.onload=()=>{const b=document.getElementById('qrcode');b.innerHTML='';new QRCode(b,{text:u.href,width:260,height:260,colorDark:'#081722',colorLight:'#fff',correctLevel:QRCode.CorrectLevel.H})};document.body.appendChild(s)}

const p=document.body.dataset.page;if(p==='home')home();if(p==='about')about();if(p==='projects')listing('project');if(p==='actions')listing('action');if(p==='team')team();if(p==='gallery')gallery();if(p==='project-detail')detail(getProject(new URLSearchParams(location.search).get('id')),'project');if(p==='action-detail')detail(getAction(new URLSearchParams(location.search).get('id')),'action');if(p==='qr')qr();
